CREATE TABLE CLIENTE(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  CIDADE VARCHAR(255) NOT NULL,
  ESTADO VARCHAR(255) NOT NULL
);

CREATE TABLE PEDIDOS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_CLIENTE INT,
  DIA DATE NOT NULL,
  PRECO DECIMAL(10,2),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);



CREATE TABLE PRODUTOS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  PRECO DECIMAL(10, 2) NOT NULL,
  ESTOQUE INT NOT NULL
  );
  
  
  
  CREATE TABLE VENDEDORES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
    );
    
    CREATE TABLE VENDAS (
      ID INT PRIMARY KEY AUTO_INCREMENT,
      ID_VENDEDOR INT,
      VALOR_VENDA DECIMAL(10, 2) NOT NULL,
      FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID)
      );
      
      
      CREATE VIEW VW_CLIENTES_PR AS
      SELECT 
      NOME,
      CIDADE
      FROM CLIENTE
      WHERE CLIENTE.ESTADO = "PR";
      CREATE VIEW VW_PEDIDOS_CLIENTES AS
      SELECT 
      C.NOME AS NOME_CLIENTE,
      P.DIA AS DATA_PEDIDO,
      P.PRECO AS VALOR_PEDIDO
      FROM PEDIDOS P
      INNER JOIN CLIENTE C ON P.ID_CLIENTE = C.ID;
      
      CREATE VIEW VW_TOTAL_CLIENTES AS
      SELECT 
      C.NOME,
      COUNT(P.ID) AS QUANTIDADE_PEDIDOS,
      SUM(P.PRECO) AS VALOR_TOTAL_GASTO
      FROM CLIENTE C
      LEFT JOIN PEDIDOS P ON C.ID = P.ID_CLIENTE
      GROUP BY C.ID, C.NOME;
      
      CREATE VIEW VW_VALOR_ESTOQUE AS
      SELECT 
      NOME,
      PRECO AS PRECO_UNITARIO,
      ESTOQUE AS QUANTIDADE_EM_ESTOQUE,
      (PRECO * ESTOQUE) AS VALOR_TOTAL
      FROM PRODUTOS;
      
      CREATE VIEW VW_DESEMPENHO_VENDEDORES AS
      SELECT 
      V.NOME AS NOME_VENDEDOR,
      COUNT(VN.ID) AS QUANTIDADE_VENDAS,
      SUM(VN.VALOR_VENDA) AS VALOR_TOTAL_VENDIDO,
      AVG(VN.VALOR_VENDA) AS VALOR_MEDIO_VENDAS,
      MAX(VN.VALOR_VENDA) AS MAIOR_VENDA_REALIZADA
      FROM VENDEDORES V
      LEFT JOIN VENDAS VN ON V.ID = VN.ID_VENDEDOR
      GROUP BY V.ID, V.NOME;
      
      INSERT INTO CLIENTE VALUES
      (NULL,"KAIKE","PINDAMONHAMGABA","PR"),
      (NULL,"MARCOS","ROGERIO","PR"),
      (NULL,"MARIA","CURITIBA","PR"),
      (NULL,"ISA","MARINGA","SP"),
      (NULL,"ISAK","PINDAMONHAMGABA","PR");
      
      INSERT INTO PEDIDOS VALUES
      (NULL, 1, '2026-10-01', 50.00),
      (NULL, 2, '2026-09-30', 20.50),
      (NULL, 3, '2026-10-01', 9.90),
      (NULL, 4, '2026-09-28', 40.00),
      (NULL, 5, '2026-09-29', 10.00),
      (NULL, 1, '2026-09-25', 85.00),
      (NULL, 2, '2026-09-26', 20.00),
      (NULL, 1, '2026-09-27', 10.20),
      (NULL, 3, '2026-09-28', 45.00),
      (NULL, 4, '2026-09-29', 50.00);
      
      INSERT INTO PRODUTOS VALUES 
      (NULL, 'Notebook', 3500.00, 10),
      (NULL, 'Mouse Sem Fio', 89.90, 50),
      (NULL, 'Teclado Mecânico', 250.00, 25),
      (NULL, 'Monitor 24', 999.00, 15),
      (NULL, 'Fone de Ouvido', 120.50, 40);

      INSERT INTO VENDEDORES VALUES 
      (NULL, 'Marcos Ribeiro'), 
      (NULL, 'Juliana Paes'), 
      (NULL, 'Roberto Carlos');
      
      INSERT INTO VENDAS VALUES 
      (NULL, 1, 500.00), (NULL, 1, 1200.00), (NULL, 1, 350.00), (NULL, 1, 800.00),
      (NULL, 2, 1500.00), (NULL, 2, 2200.00), (NULL, 2, 150.00),
      (NULL, 3, 90.00), (NULL, 3, 450.00), (NULL, 3, 600.00);

      SELECT * FROM VW_CLIENTES_PR;
      SELECT * FROM VW_PEDIDOS_CLIENTES;
      SELECT * FROM VW_VALOR_ESTOQUE;
      SELECT * FROM VW_TOTAL_CLIENTES;
      SELECT * FROM VW_DESEMPENHO_VENDEDORES;
    
